### ISSUE TITLE
Tree shaking / code splitting

### ISSUE THREAD

**Issue by lovrozagar** [huozhi/bunchee#488] opened 2024-03-11 18:26 UTC
I am building a component library for Next.js, using bunchee to compile but when using only one component out of many in the consumer app, my whole library is included in the built app bundle size. Looking at the build file that bunchee generates for the component library, code is split into many smaller files, I am using "use client" directive somewhere and those components are separate files too.

Maybe I am missing something. It would be good to note what is needed for tree shaking in the docs as I am unable to find more info on this topic.

![Code_rqXRvvjZXk](https://github.com/huozhi/bunchee/assets/86857639/d167aeee-3c82-4de3-9f3f-ccfbed130157)

**Comment by huozhi** [comment] 2024-03-18 00:40
Can you share a reproduction with both library and your next.js code? It has few factors that could effect the tree-shaking

**Comment by lovrozagar** [comment] 2024-06-02 21:28
Sorry for the late reply.

Sure here is the library repo: https://github.com/lovrozagar/renderui-core/blob/main/package.json

and nextjs starter with one import to showcase the issue: https://github.com/lovrozagar/bunchee-treshake-reproduction

**Comment by lovrozagar** [comment] 2024-07-30 12:32
Is there any news for the treeshaking?

**Comment by huozhi** [comment] 2024-07-31 10:15
It's more like a Next.js optimization issue. Have you tried with the latest Next.js version? It could be related to the client components tree-shaking on Next.js, there're a lot of updates after the version in the screenshot.

**Comment by lovrozagar** [comment] 2024-08-17 22:03
I have tried and tested with the newest Nextjs 15 version, the result is still the same, whole library is included in the bundle size of pages where only one component was used.

**Comment by huozhi** [comment] 2024-08-31 20:48
There're a few expressions could cause side effects in the library, for instance the `K.displayName = 'ModalTitle'`. These could cause the tree-shaking marking the module as containing "side effects" and cannot process.

One small thing in the package that since you're using `type: module`, then you only need to keep `dist/index.js`, it's same as `dist/index.mjs`, the exports condition can be dropped there as it's duplicated to `main` + `type: "module"`.

I'll close this for now as it's a specific library issue

**Closed by huozhi** 2024-08-31 20:48 UTC
